
RGraph=window.RGraph||{isRGraph:true};RGraph.Drawing=RGraph.Drawing||{};RGraph.Drawing.YAxis=function(conf)
{if(typeof conf==='object'&&typeof conf.x==='number'&&typeof conf.id==='string'){var id=conf.id
var x=conf.x;var parseConfObjectForOptions=true;}else{var id=conf;var x=arguments[1];}
this.id=id;this.canvas=document.getElementById(this.id);this.context=this.canvas.getContext("2d");this.canvas.__object__=this;this.x=x;this.coords=[];this.coordsText=[];this.original_colors=[];this.maxLabelLength=0;this.firstDraw=true;this.type='drawing.yaxis';this.isRGraph=true;this.uid=RGraph.CreateUID();this.canvas.uid=this.canvas.uid?this.canvas.uid:RGraph.CreateUID();this.properties={'chart.margin.top':25,'chart.margin.bottom':30,'chart.colors':['black'],'chart.title':'','chart.title.color':null,'chart.title.font':null,'chart.title.size':null,'chart.title.bold':null,'chart.title.italic':null,'chart.text.font':'Arial, Verdana, sans-serif','chart.text.size':12,'chart.text.color':'black','chart.text.bold':false,'chart.text.italic':false,'chart.text.accessible':true,'chart.text.accessible.overflow':'visible','chart.text.accessible.pointerevents':false,'chart.yaxis':true,'chart.yaxis.tickmarks.count':5,'chart.yaxis.labels.count':5,'chart.yaxis.labels.specific':null,'chart.yaxis.labels.font':null,'chart.yaxis.labels.size':null,'chart.yaxis.labels.color':null,'chart.yaxis.labels.bold':null,'chart.yaxis.labels.italic':null,'chart.yaxis.tickmarks.align':'left','chart.yaxis.scale.min':0,'chart.yaxis.scale.max':null,'chart.yaxis.scale.formatter':null,'chart.yaxis.scale.decimals':0,'chart.yaxis.scale.point':'.','chart.yaxis.scale.thousand':',','chart.yaxis.scale.invert':false,'chart.yaxis.scale.zerostart':true,'chart.yaxis.scale.visible':true,'chart.yaxis.scale.units.pre':'','chart.yaxis.scale.units.post':'','chart.yaxis.tickmarks.last.top':true,'chart.yaxis.tickmarks.last.bottom':true,'chart.linewidth':1,'chart.tooltips':null,'chart.tooltips.effect':'fade','chart.tooltips.css.class':'RGraph_tooltip','chart.tooltips.event':'onclick','chart.xaxis.position':'bottom','chart.events.click':null,'chart.events.mousemove':null,'chart.clearto':'rgba(0,0,0,0)'}
if(!this.canvas){alert('[DRAWING.YAXIS] No canvas support');return;}
this.$0={};if(!this.canvas.__rgraph_aa_translated__){this.context.translate(0.5,0.5);this.canvas.__rgraph_aa_translated__=true;}
var RG=RGraph,ca=this.canvas,co=ca.getContext('2d'),prop=this.properties,pa2=RG.path2,win=window,doc=document,ma=Math
if(RG.Effects&&typeof RG.Effects.decorate==='function'){RG.Effects.decorate(this);}
this.set=this.Set=function(name)
{var value=typeof arguments[1]==='undefined'?null:arguments[1];if(arguments.length===1&&typeof name==='object'){RG.parseObjectStyleConfig(this,name);return this;}
if(name.substr(0,6)!='chart.'){name='chart.'+name;}
while(name.match(/([A-Z])/)){name=name.replace(/([A-Z])/,'.'+RegExp.$1.toLowerCase());}
prop[name]=value;return this;};this.get=this.Get=function(name)
{if(name.substr(0,6)!='chart.'){name='chart.'+name;}
while(name.match(/([A-Z])/)){name=name.replace(/([A-Z])/,'.'+RegExp.$1.toLowerCase());}
return prop[name.toLowerCase()];};this.draw=this.Draw=function()
{RG.fireCustomEvent(this,'onbeforedraw');this.marginTop=prop['chart.margin.top'];this.marginBottom=prop['chart.margin.bottom'];this.coordsText=[];if(!prop['chart.text.color'])prop['chart.text.color']=prop['chart.colors'][0];if(!prop['chart.title.color'])prop['chart.title.color']=prop['chart.text.color'];if(!this.colorsParsed){this.parseColors();this.colorsParsed=true;}
this.drawYAxis();RG.installEventListeners(this);if(this.firstDraw){this.firstDraw=false;RG.fireCustomEvent(this,'onfirstdraw');this.firstDrawFunc();}
RG.FireCustomEvent(this,'ondraw');return this;};this.exec=function(func)
{func(this);return this;};this.getObjectByXY=function(e)
{if(this.getShape(e)){return this;}};this.getShape=function(e)
{var mouseXY=RG.getMouseXY(e);var mouseX=mouseXY[0];var mouseY=mouseXY[1];if(mouseX>=this.x-(prop['chart.tickmarks.align']=='right'?0:this.getWidth())&&mouseX<=this.x+(prop['chart.tickmarks.align']=='right'?this.getWidth():0)&&mouseY>=this.marginTop&&mouseY<=(ca.height-this.marginBottom)){var x=this.x;var y=this.marginTop;var w=15;;var h=ca.height-this.marginTop-this.marginBottom;return{0:this,1:x,2:y,3:w,4:h,5:0,'object':this,'x':x,'y':y,'width':w,'height':h,'index':0,'tooltip':prop['chart.tooltips']?prop['chart.tooltips'][0]:null};}
return null;};this.highlight=this.Highlight=function(shape)
{if(typeof prop['chart.highlight.style']==='function'){(prop['chart.highlight.style'])(shape);}};this.parseColors=function()
{if(this.original_colors.length===0){this.original_colors['chart.yaxis.labels.color']=RG.arrayClone(prop['chart.yaxis.labels.color']);this.original_colors['chart.title.color']=RG.arrayClone(prop['chart.title.color']);this.original_colors['chart.text.color']=RG.arrayClone(prop['chart.text.color']);this.original_colors['chart.colors']=RG.arrayClone(prop['chart.colors']);}
prop['chart.yaxis.labels.color']=this.parseSingleColorForGradient(prop['chart.yaxis.labels.color']);prop['chart.title.color']=this.parseSingleColorForGradient(prop['chart.title.color']);prop['chart.text.color']=this.parseSingleColorForGradient(prop['chart.text.color']);prop['chart.colors'][0]=this.parseSingleColorForGradient(prop['chart.colors'][0]);};this.reset=function()
{};this.parseSingleColorForGradient=function(color)
{if(!color){return color;}
if(typeof color==='string'&&color.match(/^gradient\((.*)\)$/i)){if(color.match(/^gradient\(({.*})\)$/i)){return RGraph.parseJSONGradient({object:this,def:RegExp.$1});}
var parts=RegExp.$1.split(':');var grad=co.createLinearGradient(0,prop['chart.margin.top'],0,ca.height-this.marginBottom);var diff=1/(parts.length-1);grad.addColorStop(0,RG.trim(parts[0]));for(var j=1;j<parts.length;++j){grad.addColorStop(j*diff,RG.trim(parts[j]));}}
return grad?grad:color;};this.drawYAxis=this.DrawYAxis=function()
{var x=this.x,y=this.marginTop,height=ca.height-this.marginBottom-this.marginTop,min=+prop['chart.yaxis.scale.min']?+prop['chart.yaxis.scale.min']:0,max=+prop['chart.yaxis.scale.max'],title=prop['chart.yaxis.title']?prop['chart.yaxis.title']:'',color=prop['chart.colors']?prop['chart.colors'][0]:'black',title_color=prop['chart.yaxis.title.color']?prop['chart.yaxis.title.color']:color,label_color=prop['chart.text.color']?prop['chart.text.color']:color,numticks=typeof(prop['chart.yaxis.tickmarks.count'])=='number'?prop['chart.yaxis.tickmarks.count']:10,labels_specific=prop['chart.yaxis.labels.specific'],numlabels=prop['chart.yaxis.labels.count']?prop['chart.yaxis.labels.count']:5,font=prop['chart.text.font']?prop['chart.text.font']:'Arial, Verdana, sans-serif',size=prop['chart.text.size']?prop['chart.text.size']:12
align=typeof(prop['chart.yaxis.tickmarks.align'])=='string'?prop['chart.yaxis.tickmarks.align']:'left',formatter=prop['chart.yaxis.scale.formatter'],decimals=prop['chart.yaxis.scale.decimals'],invert=prop['chart.yaxis.scale.invert'],scale_visible=prop['chart.yaxis.scale.visible'],units_pre=prop['chart.yaxis.scale.units.pre'],units_post=prop['chart.yaxis.scale.units.post'],linewidth=prop['chart.linewidth']?prop['chart.linewidth']:1,notopendtick=!prop['chart.yaxis.tickmarks.last.top'],nobottomendtick=!prop['chart.yaxis.tickmarks.last.bottom'],yaxis=prop['chart.yaxis'],xaxispos=prop['chart.xaxis.position']
co.lineWidth=linewidth+0.001;co.strokeStyle=color;if(yaxis){pa2(co,'b m % % l % % s %',Math.round(x),y,Math.round(x),y+height,color);if(numticks){var gap=(xaxispos=='center'?height/2:height)/numticks;var halfheight=height/2;co.beginPath();for(var i=(notopendtick?1:0);i<=(numticks-(nobottomendtick||xaxispos=='center'?1:0));++i){pa2(co,['m',align=='right'?x+3:x-3,Math.round(y+(gap*i)),'l',x,Math.round(y+(gap*i))]);}
if(xaxispos=='center'){for(var i=1;i<=numticks-(nobottomendtick?1:0);++i){pa2(co,['m',align=='right'?x+3:x-3,Math.round(y+halfheight+(gap*i)),'l',x,Math.round(y+halfheight+(gap*i))]);}}
co.stroke();}}
co.fillStyle=label_color;var text_len=0;if(scale_visible){if(labels_specific&&labels_specific.length){var text_len=0;for(var i=0,len=labels_specific.length;i<len;i+=1){text_len=ma.max(text_len,co.measureText(labels_specific[i]).width);}
var textConf=RG.getTextConf({object:this,prefix:'chart.yaxis.labels'});for(var i=0,len=labels_specific.length;i<len;++i){var gap=(len-1)>0?(height/(len-1)):0;if(xaxispos=='center'){gap/=2;}
RG.text2(this,{font:textConf.font,size:textConf.size,bold:textConf.bold,italic:textConf.italic,color:textConf.color,x:x-(align=='right'?-5:5),y:(i*gap)+this.marginTop,text:labels_specific[i],valign:'center',halign:align=='right'?'left':'right',tag:'scale'});this.maxLabelLength=ma.max(this.maxLabelLength,co.measureText(labels_specific[i]).width);}
if(xaxispos=='center'){for(var i=(labels_specific.length-2);i>=0;--i){RG.text2(this,{font:textConf.font,size:textConf.size,bold:textConf.bold,italic:textConf.italic,color:textConf.color,x:x-(align=='right'?-5:5),y:ca.height-this.marginBottom-(i*gap),text:labels_specific[i],valign:'center',halign:align=='right'?'left':'right',tag:'scale'});}}}else{var textConf=RG.getTextConf({object:this,prefix:'chart.yaxis.labels'});for(var i=0;i<=numlabels;++i){var original=((max-min)*((numlabels-i)/numlabels))+min;if(original==0&&prop['chart.yaxis.scale.zerostart']==false){continue;}
var text=RG.numberFormat({object:this,number:original.toFixed(original===0?0:decimals),unitspre:units_pre,unitspost:units_post,point:prop['chart.yaxis.scale.point'],thousand:prop['chart.yaxis.scale.thousand']});var text=String(typeof(formatter)=='function'?formatter(this,original):text);var text_len=ma.max(text_len,co.measureText(text).width);this.maxLabelLength=text_len;if(invert){var y=height-((height/numlabels)*i);}else{var y=(height/numlabels)*i;}
if(prop['chart.xaxis.position']=='center'){y=y/2;}
text=text.replace(/^-,([0-9])/,'-$1');RG.text2(this,{font:textConf.font,size:textConf.size,bold:textConf.bold,italic:textConf.italic,color:textConf.color,x:x-(align=='right'?-5:5),y:y+this.marginTop,text:text,valign:'center',halign:align=='right'?'left':'right',tag:'scale'});if(prop['chart.xaxis.position']=='center'&&i<numlabels){RG.Text2(this,{font:textConf.font,size:textConf.size,bold:textConf.bold,italic:textConf.italic,color:textConf.color,x:x-(align=='right'?-5:5),y:ca.height-this.marginBottom-y,text:'-'+text,valign:'center',halign:align=='right'?'left':'right',tag:'scale'});}}}}
if(title){co.beginPath();co.fillStyle=title_color;if(labels_specific){var width=0;for(var i=0,len=labels_specific.length;i<len;i+=1){width=Math.max(width,co.measureText(labels_specific[i]).width);}}else{var m=RG.measureText(prop['chart.yaxis.scale.units.pre']+prop['chart.yaxis.scale.max'].toFixed(prop['chart.yaxis.scale.decimals'])+prop['chart.yaxis.scale.units.post']),width=m[0];}
var textConf=RG.getTextConf({object:this,prefix:'chart.yaxis.title'});RG.text2(this,{font:textConf.font,size:textConf.size,bold:textConf.bold,italic:textConf.italic,color:textConf.color,x:align=='right'?x+width+13:x-width-13,y:height/2+this.marginTop,text:title,valign:'bottom',halign:'center',angle:align=='right'?90:-90,accessible:false});co.stroke();}};this.getWidth=function()
{var width=this.maxLabelLength;if(prop['chart.yaxis.title']&&prop['chart.yaxis.title'].length){width+=(prop['chart.text.size']*1.5);}
this.width=width;return width;};this.on=function(type,func)
{if(type.substr(0,2)!=='on'){type='on'+type;}
if(typeof this[type]!=='function'){this[type]=func;}else{RG.addCustomEventListener(this,type,func);}
return this;};this.firstDrawFunc=function()
{};RG.register(this);if(parseConfObjectForOptions){RG.parseObjectStyleConfig(this,conf.options);}};